<?php

/**
 * MIT License. This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Propel\Tests\Generator\Platform;

use PHPUnit\Framework\Attributes\DataProvider;
use Propel\Generator\Model\Column;
use Propel\Generator\Model\ColumnDefaultValue;
use Propel\Generator\Model\Database;
use Propel\Generator\Model\IdMethod;
use Propel\Generator\Model\IdMethodParameter;
use Propel\Generator\Model\Index;
use Propel\Generator\Model\PropelTypes;
use Propel\Generator\Model\Table;
use Propel\Generator\Model\Unique;
use Propel\Generator\Platform\PgsqlPlatform;
use Propel\Generator\Platform\PlatformInterface;

class PgsqlPlatformTest extends PlatformTestProvider
{
    /**
     * Get the Platform object for this class
     *
     * @return \Propel\Generator\Platform\PgsqlPlatform
     */
    protected function getPlatform(): PlatformInterface
    {
        return new PgsqlPlatform();
    }

    /**
     * @return void
     */
    public function testGetSequenceNameDefault()
    {
        $table = new Table('foo');
        $table->setIdMethod(IdMethod::NATIVE);
        $col = new Column('bar');
        $col->getDomain()->copy($this->getPlatform()->getDomainForType('INTEGER'));
        $col->setAutoIncrement(true);
        $table->addColumn($col);
        $expected = 'foo_bar_seq';
        $this->assertEquals($expected, $this->getPlatform()->getSequenceName($table));
    }

    /**
     * @return void
     */
    public function testGetSequenceNameCustom()
    {
        $table = new Table('foo');
        $table->setIdMethod(IdMethod::NATIVE);
        $idMethodParameter = new IdMethodParameter();
        $idMethodParameter->setValue('foo_sequence');
        $table->addIdMethodParameter($idMethodParameter);
        $table->setIdMethod(IdMethod::NATIVE);
        $col = new Column('bar');
        $col->getDomain()->copy($this->getPlatform()->getDomainForType('INTEGER'));
        $col->setAutoIncrement(true);
        $table->addColumn($col);
        $expected = 'foo_sequence';
        $this->assertEquals($expected, $this->getPlatform()->getSequenceName($table));
    }

    /**
     * @dataProvider providerForTestGetAddTablesDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTablesDDL')]
    public function testGetAddTablesDDL($schema)
    {
        $database = $this->getDatabaseFromSchema($schema);
        $expected = <<<EOF

BEGIN;

-----------------------------------------------------------------------
-- book
-----------------------------------------------------------------------

DROP TABLE IF EXISTS "book" CASCADE;

CREATE TABLE "book"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "author_id" INTEGER,
    PRIMARY KEY ("id")
);

CREATE INDEX "book_title_idx" ON "book" ("title");

-----------------------------------------------------------------------
-- author
-----------------------------------------------------------------------

DROP TABLE IF EXISTS "author" CASCADE;

CREATE TABLE "author"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" VARCHAR(100),
    "last_name" VARCHAR(100),
    PRIMARY KEY ("id")
);

ALTER TABLE "book" ADD CONSTRAINT "book_fk_ea464c"
    FOREIGN KEY ("author_id")
    REFERENCES "author" ("id");

COMMIT;

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTablesDDL($database));
    }

    /**
     * @dataProvider providerForTestGetAddTablesSkipSQLDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTablesSkipSQLDDL')]
    public function testGetAddTablesDDLSkipSQL($schema)
    {
        $database = $this->getDatabaseFromSchema($schema);
        $expected = '';
        $this->assertEquals($expected, $this->getPlatform()->getAddTablesDDL($database));
    }

    /**
     * @return void
     */
    public function testGetAddTablesDDLSchemasVendor()
    {
        $schema = <<<EOF
<database name="test" identifierQuoting="true">
    <table name="table1">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true"/>
        <vendor type="pgsql">
            <parameter name="schema" value="Woopah"/>
        </vendor>
    </table>
    <table name="table2">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true"/>
    </table>
    <table name="table3">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true"/>
        <vendor type="pgsql">
            <parameter name="schema" value="Yipee"/>
        </vendor>
    </table>
</database>
EOF;
        $database = $this->getDatabaseFromSchema($schema);
        $expected = <<<EOF

BEGIN;

CREATE SCHEMA "Woopah";

CREATE SCHEMA "Yipee";

-----------------------------------------------------------------------
-- table1
-----------------------------------------------------------------------

SET search_path TO "Woopah";

DROP TABLE IF EXISTS "table1" CASCADE;

SET search_path TO public;

SET search_path TO "Woopah";

CREATE TABLE "table1"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("id")
);

SET search_path TO public;

-----------------------------------------------------------------------
-- table2
-----------------------------------------------------------------------

DROP TABLE IF EXISTS "table2" CASCADE;

CREATE TABLE "table2"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("id")
);

-----------------------------------------------------------------------
-- table3
-----------------------------------------------------------------------

SET search_path TO "Yipee";

DROP TABLE IF EXISTS "table3" CASCADE;

SET search_path TO public;

SET search_path TO "Yipee";

CREATE TABLE "table3"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("id")
);

SET search_path TO public;

COMMIT;

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTablesDDL($database));
    }

    /**
     * @dataProvider providerForTestGetAddTablesDDLSchema
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTablesDDLSchema')]
    public function testGetAddTablesDDLSchemas($schema)
    {
        $database = $this->getDatabaseFromSchema($schema);
        $expected = <<<EOF

BEGIN;

-----------------------------------------------------------------------
-- x.book
-----------------------------------------------------------------------

DROP TABLE IF EXISTS "x"."book" CASCADE;

CREATE TABLE "x"."book"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "author_id" INTEGER,
    PRIMARY KEY ("id")
);

CREATE INDEX "book_title_idx" ON "x"."book" ("title");

-----------------------------------------------------------------------
-- y.author
-----------------------------------------------------------------------

DROP TABLE IF EXISTS "y"."author" CASCADE;

CREATE TABLE "y"."author"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" VARCHAR(100),
    "last_name" VARCHAR(100),
    PRIMARY KEY ("id")
);

-----------------------------------------------------------------------
-- x.book_summary
-----------------------------------------------------------------------

DROP TABLE IF EXISTS "x"."book_summary" CASCADE;

CREATE TABLE "x"."book_summary"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "book_id" INTEGER NOT NULL,
    "summary" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "x"."book" ADD CONSTRAINT "book_fk_4444ca"
    FOREIGN KEY ("author_id")
    REFERENCES "y"."author" ("id");

ALTER TABLE "x"."book_summary" ADD CONSTRAINT "book_summary_fk_23450f"
    FOREIGN KEY ("book_id")
    REFERENCES "x"."book" ("id")
    ON DELETE CASCADE;

COMMIT;

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTablesDDL($database));
    }

    /**
     * @dataProvider providerForTestGetAddTableDDLSimplePK
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTableDDLSimplePK')]
    public function testGetAddTableDDLSimplePK($schema)
    {
        $table = $this->getTableFromSchema($schema);
        $expected = <<<EOF

CREATE TABLE "foo"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bar" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

COMMENT ON TABLE "foo" IS 'This is foo table';

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @dataProvider providerForTestGetAddTableDDLCompositePK
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTableDDLCompositePK')]
    public function testGetAddTableDDLCompositePK($schema)
    {
        $table = $this->getTableFromSchema($schema);
        $expected = <<<EOF

CREATE TABLE "foo"
(
    "foo" INTEGER NOT NULL,
    "bar" INTEGER NOT NULL,
    "baz" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("foo","bar")
);

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @dataProvider providerForTestGetAddTableDDLUniqueIndex
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTableDDLUniqueIndex')]
    public function testGetAddTableDDLUniqueIndex($schema)
    {
        $table = $this->getTableFromSchema($schema);
        $expected = <<<EOF

CREATE TABLE "foo"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bar" INTEGER,
    PRIMARY KEY ("id"),
    CONSTRAINT "foo_bar_uniq" UNIQUE ("bar")
);

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @return void
     */
    public function testGetAddTableDDLSchemaVendor()
    {
        $schema = <<<EOF
<database name="test" identifierQuoting="true">
    <table name="foo">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true"/>
        <vendor type="pgsql">
            <parameter name="schema" value="Woopah"/>
        </vendor>
    </table>
</database>
EOF;
        $table = $this->getTableFromSchema($schema);
        $expected = <<<EOF

SET search_path TO "Woopah";

CREATE TABLE "foo"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("id")
);

SET search_path TO public;

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @dataProvider providerForTestGetAddTableDDLSchema
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTableDDLSchema')]
    public function testGetAddTableDDLSchema($schema)
    {
        $table = $this->getTableFromSchema($schema, 'Woopah.foo');
        $expected = <<<EOF

CREATE TABLE "Woopah"."foo"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bar" INTEGER,
    PRIMARY KEY ("id")
);

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @return void
     */
    public function testGetAddTableDDLSequence()
    {
        $schema = <<<EOF
<database name="test" identifierQuoting="true">
    <table name="foo">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true"/>
        <id-method-parameter value="my_custom_sequence_name"/>
    </table>
</database>
EOF;
        $table = $this->getTableFromSchema($schema);
        $expected = <<<EOF

CREATE SEQUENCE "my_custom_sequence_name";

CREATE TABLE "foo"
(
    "id" INTEGER DEFAULT nextval('my_custom_sequence_name'::regclass) NOT NULL,
    PRIMARY KEY ("id")
);

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @return void
     */
    public function testGetAddTableDDLColumnComments()
    {
        $schema = <<<EOF
<database name="test" identifierQuoting="true">
    <table name="foo">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true" description="identifier column"/>
        <column name="bar" type="INTEGER" description="your name here"/>
    </table>
</database>
EOF;
        $table = $this->getTableFromSchema($schema);
        $expected = <<<EOF

CREATE TABLE "foo"
(
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bar" INTEGER,
    PRIMARY KEY ("id")
);

COMMENT ON COLUMN "foo"."id" IS 'identifier column';

COMMENT ON COLUMN "foo"."bar" IS 'your name here';

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @return void
     */
    public function testGetDropTableDDL()
    {
        $table = new Table('foo');
        $expected = '
DROP TABLE IF EXISTS "foo" CASCADE;
';
        $this->assertEquals($expected, $this->getPlatform()->getDropTableDDL($table));
    }

    /**
     * @return void
     */
    public function testGetDropTableDDLSchemaVendor()
    {
        $schema = <<<EOF
<database name="test">
    <table name="foo">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true"/>
        <vendor type="pgsql">
            <parameter name="schema" value="Woopah"/>
        </vendor>
    </table>
</database>
EOF;
        $table = $this->getTableFromSchema($schema);
        $expected = <<<EOF

SET search_path TO "Woopah";

DROP TABLE IF EXISTS "foo" CASCADE;

SET search_path TO public;

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getDropTableDDL($table));
    }

    /**
     * @dataProvider providerForTestGetAddTableDDLSchema
     *
     * @return void
     */
    #[DataProvider('providerForTestGetAddTableDDLSchema')]
    public function testGetDropTableDDLSchema($schema)
    {
        $table = $this->getTableFromSchema($schema, 'Woopah.foo');
        $expected = <<<EOF

DROP TABLE IF EXISTS "Woopah"."foo" CASCADE;

EOF;
        $this->assertEquals($expected, $this->getPlatform()->getDropTableDDL($table));
    }

    /**
     * @return void
     */
    public function testGetDropTableWithSequenceDDL()
    {
        $table = new Table('foo');
        $idMethodParameter = new IdMethodParameter();
        $idMethodParameter->setValue('foo_sequence');
        $table->addIdMethodParameter($idMethodParameter);
        $table->setIdMethod(IdMethod::NATIVE);
        $expected = '
DROP TABLE IF EXISTS "foo" CASCADE;

DROP SEQUENCE "foo_sequence";
';
        $this->assertEquals($expected, $this->getPlatform()->getDropTableDDL($table));
    }

    /**
     * @return void
     */
    public function testGetColumnDDL()
    {
        $c = new Column('foo');
        $c->getDomain()->copy($this->getPlatform()->getDomainForType('DOUBLE'));
        $c->getDomain()->replaceScale(2);
        $c->getDomain()->replaceSize(3);
        $c->setNotNull(true);
        $c->getDomain()->setDefaultValue(new ColumnDefaultValue(123, ColumnDefaultValue::TYPE_VALUE));
        $expected = '"foo" DOUBLE PRECISION DEFAULT 123 NOT NULL';
        $this->assertEquals($expected, $this->getPlatform()->getColumnDDL($c));
    }

    /**
     * @return void
     */
    public function testGetColumnDDLAutoIncrement()
    {
        $database = new Database();
        $database->setPlatform($this->getPlatform());
        $table = new Table('foo_table');
        $table->setIdMethod(IdMethod::NATIVE);
        $database->addTable($table);
        $column = new Column('foo');
        $column->getDomain()->copy($this->getPlatform()->getDomainForType(PropelTypes::BIGINT));
        $column->setAutoIncrement(true);
        $table->addColumn($column);
        $expected = '"foo" BIGINT GENERATED BY DEFAULT AS IDENTITY';
        $this->assertEquals($expected, $this->getPlatform()->getColumnDDL($column));
    }

    /**
     * @return void
     */
    public function testGetColumnDDLCustomSqlType()
    {
        $column = new Column('foo');
        $column->getDomain()->copy($this->getPlatform()->getDomainForType('DOUBLE'));
        $column->getDomain()->replaceScale(2);
        $column->getDomain()->replaceSize(3);
        $column->setNotNull(true);
        $column->getDomain()->setDefaultValue(new ColumnDefaultValue(123, ColumnDefaultValue::TYPE_VALUE));
        $column->getDomain()->replaceSqlType('DECIMAL(5,6)');
        $expected = '"foo" DECIMAL(5,6) DEFAULT 123 NOT NULL';
        $this->assertEquals($expected, $this->getPlatform()->getColumnDDL($column));
    }

    /**
     * @return void
     */
    public function testGetPrimaryKeyDDLSimpleKey()
    {
        $table = new Table('foo');
        $column = new Column('bar');
        $column->setPrimaryKey(true);
        $table->addColumn($column);
        $expected = 'PRIMARY KEY ("bar")';
        $this->assertEquals($expected, $this->getPlatform()->getPrimaryKeyDDL($table));
    }

    /**
     * @return void
     */
    public function testGetPrimaryKeyDDLCompositeKey()
    {
        $table = new Table('foo');
        $column1 = new Column('bar1');
        $column1->setPrimaryKey(true);
        $table->addColumn($column1);
        $column2 = new Column('bar2');
        $column2->setPrimaryKey(true);
        $table->addColumn($column2);
        $expected = 'PRIMARY KEY ("bar1","bar2")';
        $this->assertEquals($expected, $this->getPlatform()->getPrimaryKeyDDL($table));
    }

    /**
     * @dataProvider providerForTestPrimaryKeyDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestPrimaryKeyDDL')]
    public function testGetDropPrimaryKeyDDL($table)
    {
        $expected = '
ALTER TABLE "foo" DROP CONSTRAINT "foo_pkey";
';
        $this->assertEquals($expected, $this->getPlatform()->getDropPrimaryKeyDDL($table));
    }

    /**
     * @dataProvider providerForTestPrimaryKeyDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestPrimaryKeyDDL')]
    public function testGetAddPrimaryKeyDDL($table)
    {
        $expected = '
ALTER TABLE "foo" ADD PRIMARY KEY ("bar");
';
        $this->assertEquals($expected, $this->getPlatform()->getAddPrimaryKeyDDL($table));
    }

    /**
     * @dataProvider providerForTestGetIndexDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetIndexDDL')]
    public function testAddIndexDDL($index)
    {
        $expected = '
CREATE INDEX "babar" ON "foo" ("bar1","bar2");
';
        $this->assertEquals($expected, $this->getPlatform()->getAddIndexDDL($index));
    }

    /**
     * @dataProvider providerForTestGetUniqueIndexDDL
     *
     * @param \Propel\Generator\Model\Unique $index
     *
     * @return void
     */
    #[DataProvider('providerForTestGetUniqueIndexDDL')]
    public function testAddUniqueIndexDDL(Unique $index): void
    {
        $expected = '
ALTER TABLE "foo" ADD CONSTRAINT "babar" UNIQUE ("bar1");
';
        $this->assertEquals($expected, $this->getPlatform()->getAddIndexDDL($index));
    }

    /**
     * @return void
     */
    public function testAddPartialUniqueIndexDDL(): void
    {
        $table = new Table('postback_user_unlinks');
        $table->setIdentifierQuoting(true);
        $userIdColumn = new Column('user_id');
        $table->addColumn($userIdColumn);
        $configIdColumn = new Column('postback_config_id');
        $table->addColumn($configIdColumn);
        $index = new Unique('postback_user_unlinks_active_unique');
        $index->addColumn($userIdColumn);
        $index->addColumn($configIdColumn);
        $index->setWhere('revoked_at IS NULL');
        $table->addUnique($index);

        $expected = '
CREATE UNIQUE INDEX "postback_user_unlinks_active_unique" ON "postback_user_unlinks" ("user_id","postback_config_id") WHERE revoked_at IS NULL;
';
        $this->assertEquals($expected, $this->getPlatform()->getAddIndexDDL($index));
    }

    /**
     * @return void
     */
    public function testDropPartialUniqueIndexDDL(): void
    {
        $table = new Table('postback_user_unlinks');
        $table->setIdentifierQuoting(true);
        $userIdColumn = new Column('user_id');
        $table->addColumn($userIdColumn);
        $index = new Unique('postback_user_unlinks_active_unique');
        $index->addColumn($userIdColumn);
        $index->setWhere('revoked_at IS NULL');
        $table->addUnique($index);

        $expected = '
DROP INDEX "postback_user_unlinks_active_unique";
';
        $this->assertEquals($expected, $this->getPlatform()->getDropIndexDDL($index));
    }

    /**
     * @return void
     */
    public function testAddPartialIndexDDL(): void
    {
        $table = new Table('postback_user_unlinks');
        $table->setIdentifierQuoting(true);
        $userIdColumn = new Column('user_id');
        $table->addColumn($userIdColumn);
        $index = new Index('postback_user_unlinks_active_idx');
        $index->addColumn($userIdColumn);
        $index->setWhere('revoked_at IS NULL');
        $table->addIndex($index);

        $expected = '
CREATE INDEX "postback_user_unlinks_active_idx" ON "postback_user_unlinks" ("user_id") WHERE revoked_at IS NULL;
';
        $this->assertEquals($expected, $this->getPlatform()->getAddIndexDDL($index));
    }

    /**
     * @dataProvider providerForTestGetIndicesDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetIndicesDDL')]
    public function testAddIndicesDDL($table)
    {
        $expected = '
CREATE INDEX "babar" ON "foo" ("bar1","bar2");

CREATE INDEX "foo_index" ON "foo" ("bar1");
';
        $this->assertEquals($expected, $this->getPlatform()->getAddIndicesDDL($table));
    }

    /**
     * @return void
     */
    public function testAddIndicesDDLIncludesPartialUniqueIndex(): void
    {
        $table = new Table('postback_user_unlinks');
        $table->setIdentifierQuoting(true);
        $userIdColumn = new Column('user_id');
        $table->addColumn($userIdColumn);
        $configIdColumn = new Column('postback_config_id');
        $table->addColumn($configIdColumn);
        $index = new Unique('postback_user_unlinks_active_unique');
        $index->addColumn($userIdColumn);
        $index->addColumn($configIdColumn);
        $index->setWhere('revoked_at IS NULL');
        $table->addUnique($index);

        $expected = '
CREATE UNIQUE INDEX "postback_user_unlinks_active_unique" ON "postback_user_unlinks" ("user_id","postback_config_id") WHERE revoked_at IS NULL;
';
        $this->assertEquals($expected, $this->getPlatform()->getAddIndicesDDL($table));
    }

    /**
     * @dataProvider providerForTestGetIndexDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetIndexDDL')]
    public function testDropIndexDDL($index)
    {
        $expected = '
DROP INDEX "babar";
';
        $this->assertEquals($expected, $this->getPlatform()->getDropIndexDDL($index));
    }

    /**
     * @dataProvider providerForTestGetIndexDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetIndexDDL')]
    public function testGetIndexDDL($index)
    {
        $expected = 'INDEX "babar" ("bar1","bar2")';
        $this->assertEquals($expected, $this->getPlatform()->getIndexDDL($index));
    }

    /**
     * @dataProvider providerForTestGetUniqueDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetUniqueDDL')]
    public function testGetUniqueDDL($index)
    {
        $expected = 'CONSTRAINT "babar" UNIQUE ("bar1","bar2")';
        $this->assertEquals($expected, $this->getPlatform()->getUniqueDDL($index));
    }

    /**
     * @dataProvider providerForTestGetForeignKeysDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetForeignKeysDDL')]
    public function testGetAddForeignKeysDDL($table)
    {
        $expected = '
ALTER TABLE "foo" ADD CONSTRAINT "foo_bar_fk"
    FOREIGN KEY ("bar_id")
    REFERENCES "bar" ("id")
    ON DELETE CASCADE;

ALTER TABLE "foo" ADD CONSTRAINT "foo_baz_fk"
    FOREIGN KEY ("baz_id")
    REFERENCES "baz" ("id")
    ON DELETE SET NULL;
';
        $this->assertEquals($expected, $this->getPlatform()->getAddForeignKeysDDL($table));
    }

    /**
     * @dataProvider providerForTestGetForeignKeyDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetForeignKeyDDL')]
    public function testGetAddForeignKeyDDL($fk)
    {
        $expected = '
ALTER TABLE "foo" ADD CONSTRAINT "foo_bar_fk"
    FOREIGN KEY ("bar_id")
    REFERENCES "bar" ("id")
    ON DELETE CASCADE;
';
        $this->assertEquals($expected, $this->getPlatform()->getAddForeignKeyDDL($fk));
    }

    /**
     * @dataProvider providerForTestGetForeignKeySkipSqlDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetForeignKeySkipSqlDDL')]
    public function testGetAddForeignKeySkipSqlDDL($fk)
    {
        $expected = '';
        $this->assertEquals($expected, $this->getPlatform()->getAddForeignKeyDDL($fk));
    }

    /**
     * @dataProvider providerForTestGetForeignKeyDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetForeignKeyDDL')]
    public function testGetDropForeignKeyDDL($fk)
    {
        $expected = '
ALTER TABLE "foo" DROP CONSTRAINT "foo_bar_fk";
';
        $this->assertEquals($expected, $this->getPlatform()->getDropForeignKeyDDL($fk));
    }

    /**
     * @dataProvider providerForTestGetForeignKeySkipSqlDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetForeignKeySkipSqlDDL')]
    public function testGetDropForeignKeySkipSqlDDL($fk)
    {
        $expected = '';
        $this->assertEquals($expected, $this->getPlatform()->getDropForeignKeyDDL($fk));
    }

    /**
     * @dataProvider providerForTestGetForeignKeyDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetForeignKeyDDL')]
    public function testGetForeignKeyDDL($fk)
    {
        $expected = 'CONSTRAINT "foo_bar_fk"
    FOREIGN KEY ("bar_id")
    REFERENCES "bar" ("id")
    ON DELETE CASCADE';
        $this->assertEquals($expected, $this->getPlatform()->getForeignKeyDDL($fk));
    }

    /**
     * @dataProvider providerForTestGetForeignKeySkipSqlDDL
     *
     * @return void
     */
    #[DataProvider('providerForTestGetForeignKeySkipSqlDDL')]
    public function testGetForeignKeySkipSqlDDL($fk)
    {
        $expected = '';
        $this->assertEquals($expected, $this->getPlatform()->getForeignKeyDDL($fk));
    }

    /**
     * @return void
     */
    public function testGetCommentBlockDDL()
    {
        $expected = "
-----------------------------------------------------------------------
-- foo bar
-----------------------------------------------------------------------
";
        $this->assertEquals($expected, $this->getPlatform()->getCommentBlockDDL('foo bar'));
    }

    /**
     * @return void
     */
    public function assertCreateTableMatches(string $expected, $schema, ?string $tableName = 'foo')
    {
        $table = $this->getTableFromSchema($schema, $tableName);
        $this->assertEquals($expected, $this->getPlatform()->getAddTableDDL($table));
    }

    /**
     * @dataProvider providerForTestCreateSchemaWithUuidColumns
     *
     * @return void
     */
    #[DataProvider('providerForTestCreateSchemaWithUuidColumns')]
    public function testCreateSchemaWithUuidColumns($schema)
    {
        $expected = <<< 'EOT'

CREATE TABLE "foo"
(
    "uuid" uuid DEFAULT vendor_specific_default() NOT NULL,
    "other_uuid" uuid,
    PRIMARY KEY ("uuid")
);

EOT;
        $this->assertCreateTableMatches($expected, $schema);
    }

    /**
     * @dataProvider providerForTestCreateSchemaWithUuidVersionMetadata
     *
     * @return void
     */
    #[DataProvider('providerForTestCreateSchemaWithUuidVersionMetadata')]
    public function testCreateSchemaWithUuidVersionMetadata($schema)
    {
        $expected = <<< 'EOT'

CREATE TABLE "foo"
(
    "uuid" uuid DEFAULT vendor_specific_default() NOT NULL,
    "other_uuid" uuid,
    PRIMARY KEY ("uuid")
);

EOT;
        $this->assertCreateTableMatches($expected, $schema);
    }

    /**
     * @dataProvider providerForTestCreateSchemaWithUuidBinaryColumns
     *
     * @return void
     */
    #[DataProvider('providerForTestCreateSchemaWithUuidBinaryColumns')]
    public function testCreateSchemaWithUuidBinaryColumns($schema)
    {
        $expected = <<< 'EOT'

CREATE TABLE "foo"
(
    "uuid-bin" BYTEA DEFAULT vendor_specific_default() NOT NULL,
    "other_uuid-bin" BYTEA,
    PRIMARY KEY ("uuid-bin")
);

EOT;
        $this->assertCreateTableMatches($expected, $schema);
    }

    /**
     * @dataProvider providerForTestCreateSchemaWithUidColumns
     *
     * @return void
     */
    #[DataProvider('providerForTestCreateSchemaWithUidColumns')]
    public function testCreateSchemaWithUidColumns($schema)
    {
        $expected = <<< 'EOT'

CREATE TABLE "foo"
(
    "uid" uuid DEFAULT vendor_specific_default() NOT NULL,
    "other_uid" uuid,
    PRIMARY KEY ("uid")
);

EOT;
        $this->assertCreateTableMatches($expected, $schema);
    }

    /**
     * @dataProvider providerForTestCreateSchemaWithUidBinaryColumns
     *
     * @return void
     */
    #[DataProvider('providerForTestCreateSchemaWithUidBinaryColumns')]
    public function testCreateSchemaWithUidBinaryColumns($schema)
    {
        $expected = <<< 'EOT'

CREATE TABLE "foo"
(
    "uid-bin" uuid DEFAULT vendor_specific_default() NOT NULL,
    "other_uid-bin" uuid,
    PRIMARY KEY ("uid-bin")
);

EOT;
        $this->assertCreateTableMatches($expected, $schema);
    }

    /**
     * @return void
     */
    public function testAddExtraIndicesUidBinaryColumn()
    {
        $schema = <<<EOF
<database name="test" identifierQuoting="true">
    <table name="foo">
        <column name="id" primaryKey="true" type="INTEGER" autoIncrement="true"/>
        <column name="uid_bin" type="UID_BINARY"/>
    </table>
</database>
EOF;
        $table = $this->getTableFromSchema($schema);
        $expected = <<< 'EOT'

CREATE INDEX "foo_uid_bin_idx" ON "foo" ("uid_bin");

EOT;

        $this->assertEquals($expected, $this->getPlatform()->getAddIndicesDDL($table));
    }

    /**
     * @dataProvider providerForTestCreateSchemaWithGeneratedUidColumns
     *
     * @return void
     */
    #[DataProvider('providerForTestCreateSchemaWithGeneratedUidColumns')]
    public function testCreateSchemaWithGeneratedUidColumns($schema)
    {
        $expected = <<< 'EOT'

CREATE TABLE "foo"
(
    "uid" uuid DEFAULT uuid_generate_v7() NOT NULL,
    "other_uid" uuid,
    PRIMARY KEY ("uid")
);

EOT;
        $this->assertCreateTableMatches($expected, $schema);
    }

    /**
     * @dataProvider providerForTestCreateSchemaWithGeneratedUidBinaryColumns
     *
     * @return void
     */
    #[DataProvider('providerForTestCreateSchemaWithGeneratedUidBinaryColumns')]
    public function testCreateSchemaWithGeneratedUidBinaryColumns($schema)
    {
        $expected = <<< 'EOT'

CREATE TABLE "foo"
(
    "uid-bin" uuid DEFAULT uuid_generate_v7() NOT NULL,
    "other_uid-bin" uuid,
    PRIMARY KEY ("uid-bin")
);

EOT;
        $this->assertCreateTableMatches($expected, $schema);
    }
}
