<?php

/**
 * MIT License. This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Propel\Tests\Generator\Model;

use PHPUnit\Framework\Attributes\DataProvider;
use Propel\Generator\Model\Index;

use function strlen;

/**
 * Unit test suite for the Index model class.
 *
 * @author Hugo Hamon <webmaster@apprendre-php.com>
 */
class IndexTest extends ModelTestCase
{
    protected static function createProviderInstance(): self
    {
        return new self('provider');
    }

    /**
     * @return void
     */
    public function testCreateNamedIndex()
    {
        $index = new Index('foo_idx');
        $index->setTable($this->getTableMock('db_books'));

        $this->assertEquals('foo_idx', $index->getName());
        $this->assertFalse($index->isUnique());
        $this->assertInstanceOf('Propel\Generator\Model\Table', $index->getTable());
        $this->assertSame('db_books', $index->getTableName());
        $this->assertCount(0, $index->getColumns());
        $this->assertFalse($index->hasColumns());
    }

    /**
     * @return void
     */
    public function testSetupObject()
    {
        $index = new Index();
        $index->setTable($this->getTableMock('books'));
        $index->loadMapping([ 'name' => 'foo_idx' ]);

        $this->assertEquals('foo_idx', $index->getName());
    }

    /**
     * @return void
     */
    #[DataProvider('provideTableSpecificAttributes')]
    public function testCreateDefaultIndexName($tableName, $maxColumnNameLength, $indexName)
    {
        $database = $this->getDatabaseMock('bookstore');
        $database
            ->expects($this->any())
            ->method('getMaxColumnNameLength')
            ->will($this->returnValue($maxColumnNameLength));

        $table = $this->getTableMock($tableName, [
            'common_name' => $tableName,
            'indices' => [ new Index(), new Index() ],
            'database' => $database,
        ]);

        $index = new Index();
        $index->setTable($table);

        $this->assertSame($indexName, $index->getName());
    }

    public static function provideTableSpecificAttributes()
    {
        return [
            [ 'books', 64, 'books_no_columns_idx' ],
            [ 'super_long_table_name', 16, 'super_84cc21_idx' ],
        ];
    }

    /**
     * @return void
     */
    public function testLongAutoGeneratedIndexNamesRemainDistinctAfterTruncation()
    {
        $database = $this->getDatabaseMock('bookstore');
        $database
            ->expects($this->any())
            ->method('getMaxColumnNameLength')
            ->will($this->returnValue(63));

        $table = $this->getTableMock('super_long_table_name_that_pushes_generated_index_names_over_limits', [
            'common_name' => 'super_long_table_name_that_pushes_generated_index_names_over_limits',
            'indices' => [],
            'database' => $database,
        ]);

        $firstIndex = new Index();
        $firstIndex->setTable($table);
        $firstIndex->setColumns([[ 'name' => 'first_column_name_that_only_differs_at_the_far_end_a' ]]);

        $secondIndex = new Index();
        $secondIndex->setTable($table);
        $secondIndex->setColumns([[ 'name' => 'first_column_name_that_only_differs_at_the_far_end_b' ]]);

        $firstName = $firstIndex->getName();
        $secondName = $secondIndex->getName();

        $this->assertSame(63, strlen($firstName));
        $this->assertSame(63, strlen($secondName));
        $this->assertNotSame($firstName, $secondName);
        $this->assertMatchesRegularExpression('/_[0-9a-f]{6}_idx$/', $firstName);
        $this->assertMatchesRegularExpression('/_[0-9a-f]{6}_idx$/', $secondName);
    }

    /**
     * @return void
     */
    public function testAutoGeneratedIndexNamesPreferTableShortName()
    {
        $database = $this->getDatabaseMock('bookstore');
        $database
            ->expects($this->any())
            ->method('getMaxColumnNameLength')
            ->will($this->returnValue(63));

        $table = $this->getTableMock('sportsbook_transactions', [
            'common_name' => 'sportsbook_transactions',
            'short_name' => 'sbtx',
            'indices' => [],
            'database' => $database,
        ]);

        $index = new Index();
        $index->setTable($table);
        $index->setColumns([
            [ 'name' => 'provider' ],
            [ 'name' => 'type' ],
            [ 'name' => 'user_id' ],
            [ 'name' => 'bet_transaction_id' ],
            [ 'name' => 'bet_order_id' ],
        ]);

        $this->assertSame(
            'sbtx_provider_type_user_id_bet_transaction_id_bet_order_id_idx',
            $index->getName(),
        );
    }

    /**
     * @return void
     */
    #[DataProvider('provideColumnDefinitions')]
    public function testAddIndexedColumns($columns)
    {
        $index = new Index();
        $index->setColumns($columns);

        $this->assertTrue($index->hasColumns());
        $this->assertCount(3, $index->getColumns());

        $this->assertSame(100, $index->getColumnSize('foo'));
        $this->assertTrue($index->hasColumnSize('foo'));

        $this->assertSame(5, $index->getColumnSize('bar'));
        $this->assertTrue($index->hasColumnSize('bar'));

        $this->assertNull($index->getColumnSize('baz'));
    }

    public static function provideColumnDefinitions()
    {
        $test = self::createProviderInstance();

        $dataset[0][] = [
            $test->getColumnMock('foo', [ 'size' => 100 ]),
            $test->getColumnMock('bar', [ 'size' => 5   ]),
            $test->getColumnMock('baz', [ 'size' => 0   ]),
        ];

        $dataset[1][] = [
            [ 'name' => 'foo', 'size' => 100 ],
            [ 'name' => 'bar', 'size' => 5 ],
            [ 'name' => 'baz', 'size' => 0 ],
        ];

        return $dataset;
    }

    /**
     * @return void
     */
    public function testResetColumnsSize()
    {
        $columns[] = $this->getColumnMock('foo', [ 'size' => 100 ]);
        $columns[] = $this->getColumnMock('bar', [ 'size' => 5   ]);

        $index = new Index();
        $index->setColumns($columns);

        $this->assertTrue($index->hasColumnSize('foo'));
        $this->assertTrue($index->hasColumnSize('bar'));

        $index->resetColumnsSize();
        $this->assertFalse($index->hasColumnSize('foo'));
        $this->assertFalse($index->hasColumnSize('bar'));
    }

    /**
     * @return void
     */
    public function testNoColumnAtFirstPosition()
    {
        $index = new Index();

        $this->assertFalse($index->hasColumnAtPosition(0, 'foo'));
    }

    /**
     * @return void
     */
    #[DataProvider('provideColumnAttributes')]
    public function testNoColumnAtPositionCaseSensitivity($name, $case)
    {
        $index = new Index();
        $index->addColumn($this->getColumnMock('foo', [ 'size' => 5 ]));

        $this->assertFalse($index->hasColumnAtPosition(0, $name, 5, $case));
    }

    public static function provideColumnAttributes()
    {
        return [
            [ 'bar', false ],
            [ 'BAR', true ],
        ];
    }

    /**
     * @return void
     */
    public function testNoSizedColumnAtPosition()
    {
        $size = 5;

        $index = new Index();
        $index->addColumn($this->getColumnMock('foo', [ 'size' => $size ]));

        $size++;
        $this->assertFalse($index->hasColumnAtPosition(0, 'foo', $size));
    }

    /**
     * @return void
     */
    public function testHasColumnAtFirstPosition()
    {
        $index = new Index();
        $index->addColumn($this->getColumnMock('foo', [ 'size' => 0 ]));

        $this->assertTrue($index->hasColumnAtPosition(0, 'foo'));
    }
}
